version: "3.0"
# services:
#   expressapp:
#     container_name: expressapp
#     build: ./backend
#     expose:
#       - 8000
#     volumes:
#       - ./backend:/usr/src/app
#   reactapp:
#     container_name: reactapp
#     build: ./frontend
#     expose:
#       - 5000
#     volumes:
#       - ./frontend:/usr/src/app
  api:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  nginx:
    depends_on:
      
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
