version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: ./backend
    expose:
      - "3001"
    volumes:
      - ./backend:/usr/src/app
  reactapp:
    container_name: reactapp
    build: ./frontend
    expose:
      - "5000"
    volumes:
      - ./frontend:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - reactapp
      - expressapp
    restart: always
  
    